[package]
authors = ["Alejandro Gaviria <mr.gaviria@gmail.com>"]
name = "argentum"
version = "0.1.0"

[dependencies]
itertools = "0.7.6"
lazy_static = "1.0.0"
pest = "1.0.6"
pest_derive = "1.0.6"
rug = "1.0.1"

[workspace]
